export const dic: Record<string, string> = {
  "Abyssal Essence": "地狱精华",
  "Acrobatic Hood": "杂技师兜帽",
  "Acrobat's Ribbon": "杂技师之带",
  "Advanced Task Badge": "高级任务徽章",
  "Alchemist's Bottoms": "炼金师的下装",
  "Alchemist's Top": "炼金师的上衣",
  "Alchemy Essence": "炼金精华",
  "Alchemy Tea": "炼金茶",
  "Amber": "琥珀",
  "Amethyst": "紫水晶",
  "Apple": "苹果",
  "Apple Gummy": "苹果软糖",
  "Apple Yogurt": "苹果酸奶",
  "Aqua Arrow": "流水箭",
  "Aqua Aura": "流水光环",
  "Aqua Essence": "海洋精华",
  "Arabica Coffee Bean": "次级咖啡豆",
  "Arcane Bow": "神秘弓",
  "Arcane Crossbow": "神秘弩",
  "Arcane Fire Staff": "神秘火法杖",
  "Arcane Log": "神秘原木",
  "Arcane Lumber": "神秘木板",
  "Arcane Nature Staff": "神秘自然法杖",
  "Arcane Reflection": "奥术反射",
  "Arcane Shield": "神秘盾",
  "Arcane Water Staff": "神秘水法杖",
  "Artisan Tea": "工匠茶",
  "Attack Coffee": "攻击咖啡",
  "Azure Alembic": "蔚蓝蒸馏器",
  "Azure Boots": "蔚蓝靴",
  "Azure Brush": "蔚蓝刷子",
  "Azure Buckler": "蔚蓝圆盾",
  "Azure Bulwark": "蔚蓝盾",
  "Azure Cheese": "蔚蓝奶酪",
  "Azure Chisel": "蔚蓝凿子",
  "Azure Enhancer": "蔚蓝强化器",
  "Azure Gauntlets": "蔚蓝臂铠",
  "Azure Hammer": "蔚蓝锤",
  "Azure Hatchet": "蔚蓝斧头",
  "Azure Helmet": "蔚蓝头盔",
  "Azure Mace": "蔚蓝狼牙棒",
  "Azure Milk": "蔚蓝牛奶",
  "Azure Needle": "蔚蓝针",
  "Azure Plate Body": "蔚蓝板甲",
  "Azure Plate Legs": "蔚蓝板甲护腿",
  "Azure Pot": "蔚蓝锅",
  "Azure Shears": "蔚蓝剪刀",
  "Azure Spatula": "蔚蓝铲子",
  "Azure Spear": "蔚蓝长枪",
  "Azure Sword": "蔚蓝剑",
  "Bag Of 10 Cowbells": "10牛铃包",
  "Bamboo Boots": "竹靴",
  "Bamboo Branch": "竹子",
  "Bamboo Fabric": "竹子布料",
  "Bamboo Gloves": "竹手套",
  "Bamboo Hat": "竹帽",
  "Bamboo Robe Bottoms": "竹布衬裙",
  "Bamboo Robe Top": "竹上衣",
  "Basic Task Badge": "基础任务徽章",
  "Bear Essence": "熊熊精华",
  "Beast Boots": "野兽靴",
  "Beast Bracers": "野兽护腕",
  "Beast Chaps": "野兽护腿",
  "Beast Hide": "野兽皮",
  "Beast Hood": "野兽兜帽",
  "Beast Leather": "野兽皮革",
  "Beast Tunic": "野兽束腰",
  "Berserk": "狂暴",
  "Birch Bow": "桦木弓",
  "Birch Crossbow": "桦木弩",
  "Birch Fire Staff": "桦木火法杖",
  "Birch Log": "白桦原木",
  "Birch Lumber": "白桦木板",
  "Birch Nature Staff": "桦木自然法杖",
  "Birch Shield": "桦木盾",
  "Birch Water Staff": "桦木水法杖",
  "Bishop's Codex": "主教之书",
  "Bishop's Scroll": "主教卷轴",
  "Black Bear Fluff": "黑熊绒",
  "Black Bear Shoes": "黑熊鞋",
  "Black Tea Leaf": "黑茶叶",
  "Blackberry": "黑莓",
  "Blackberry Cake": "黑莓蛋糕",
  "Blackberry Donut": "黑莓甜甜圈",
  "Blessed Tea": "祝福茶",
  "Blue Key Fragment": "蓝色钥匙碎片",
  "Blueberry": "蓝莓",
  "Blueberry Cake": "蓝莓蛋糕",
  "Blueberry Donut": "蓝莓甜甜圈",
  "Branch Of Insight": "明悟之枝",
  "Brewer's Bottoms": "饮品师的下装",
  "Brewer's Top": "饮品师的上衣",
  "Brewing Essence": "冲泡精华",
  "Brewing Tea": "冲泡茶",
  "Brown Key Fragment": "棕色钥匙碎片",
  "Burble Alembic": "深紫蒸馏器",
  "Burble Boots": "深紫靴",
  "Burble Brush": "深紫刷子",
  "Burble Buckler": "深紫圆盾",
  "Burble Bulwark": "深紫盾",
  "Burble Cheese": "深紫奶酪",
  "Burble Chisel": "深紫凿子",
  "Burble Enhancer": "深紫强化器",
  "Burble Gauntlets": "深紫臂铠",
  "Burble Hammer": "深紫锤",
  "Burble Hatchet": "深紫斧头",
  "Burble Helmet": "深紫头盔",
  "Burble Mace": "深紫狼牙棒",
  "Burble Milk": "深紫牛奶",
  "Burble Needle": "深紫针",
  "Burble Plate Body": "深紫板甲",
  "Burble Plate Legs": "深紫板甲护腿",
  "Burble Pot": "深紫锅",
  "Burble Shears": "深紫剪刀",
  "Burble Spatula": "深紫铲子",
  "Burble Spear": "深紫长枪",
  "Burble Sword": "深紫剑",
  "Burble Tea Leaf": "紫茶叶",
  "Burning Key Fragment": "燃烧钥匙碎片",
  "Butter Of Proficiency": "精通之油",
  "Catalyst Of Coinification": "点金催化剂",
  "Catalyst Of Decomposition": "分解催化剂",
  "Catalyst Of Transmutation": "重组催化剂",
  "Catalytic Tea": "催化茶",
  "Cedar Bow": "雪松弓",
  "Cedar Crossbow": "雪松弩",
  "Cedar Fire Staff": "雪松火法杖",
  "Cedar Log": "雪松原木",
  "Cedar Lumber": "雪松木板",
  "Cedar Nature Staff": "雪松自然法杖",
  "Cedar Shield": "雪松盾",
  "Cedar Water Staff": "雪松水法杖",
  "Celestial Alembic": "星空蒸馏器",
  "Celestial Brush": "星空刷子",
  "Celestial Chisel": "星空凿子",
  "Celestial Enhancer": "星空强化器",
  "Celestial Hammer": "星空锤",
  "Celestial Hatchet": "星空斧头",
  "Celestial Needle": "星空针",
  "Celestial Pot": "星空锅",
  "Celestial Shears": "星空剪刀",
  "Celestial Spatula": "星空铲子",
  "Centaur Boots": "半人马靴",
  "Centaur Hoof": "半人马蹄",
  "Channeling Coffee": "吟唱咖啡",
  "Chaotic Chain": "混沌锁链",
  "Chaotic Flail": "混沌连枷",
  "Cheese": "奶酪",
  "Cheese Alembic": "奶酪蒸馏器",
  "Cheese Boots": "奶酪靴",
  "Cheese Brush": "奶酪刷子",
  "Cheese Buckler": "奶酪圆盾",
  "Cheese Bulwark": "奶酪盾",
  "Cheese Chisel": "奶酪凿子",
  "Cheese Enhancer": "奶酪强化器",
  "Cheese Gauntlets": "奶酪臂铠",
  "Cheese Hammer": "奶酪锤",
  "Cheese Hatchet": "奶酪斧头",
  "Cheese Helmet": "奶酪头盔",
  "Cheese Mace": "奶酪狼牙棒",
  "Cheese Needle": "奶酪针",
  "Cheese Plate Body": "奶酪板甲",
  "Cheese Plate Legs": "奶酪板甲护腿",
  "Cheese Pot": "奶酪锅",
  "Cheese Shears": "奶酪剪刀",
  "Cheese Spatula": "奶酪铲子",
  "Cheese Spear": "奶酪长枪",
  "Cheese Sword": "奶酪剑",
  "Cheesemaker's Bottoms": "奶酪师的下装",
  "Cheesemaker's Top": "奶酪师的上衣",
  "Cheesesmithing Essence": "奶酪锻造精华",
  "Cheesesmithing Tea": "奶酪锻造茶",
  "Chef's Bottoms": "厨师的下装",
  "Chef's Top": "厨师的上衣",
  "Chimerical Chest": "奇幻宝箱",
  "Chimerical Chest Key": "奇幻宝箱钥匙",
  "Chimerical Entry Key": "奇幻钥匙",
  "Chimerical Essence": "奇幻精华",
  "Chimerical Quiver": "奇幻箭袋",
  "Chimerical Token": "奇幻代币",
  "Chrono Gloves": "时空手套",
  "Chrono Sphere": "时空球",
  "Cleave": "分裂斩(群体)",
  "Cocoon": "蚕茧",
  "Coin": "金币",
  "Collector's Boots": "收藏家靴",
  "Colossus Core": "巨像核心",
  "Colossus Plate Body": "巨像板甲",
  "Colossus Plate Legs": "巨像板甲护腿",
  "Cooking Essence": "烹饪精华",
  "Cooking Tea": "烹饪茶",
  "Cotton": "棉花",
  "Cotton Boots": "棉靴",
  "Cotton Fabric": "棉花布料",
  "Cotton Gloves": "棉手套",
  "Cotton Hat": "棉帽",
  "Cotton Robe Bottoms": "棉衬裙",
  "Cotton Robe Top": "棉布上衣",
  "Cowbell": "牛铃",
  "Crab Pincer": "蟹钳",
  "Crafter's Bottoms": "工匠的下装",
  "Crafter's Top": "工匠的上衣",
  "Crafting Essence": "制作精华",
  "Crafting Tea": "制作茶",
  "Crimson Alembic": "深红蒸馏器",
  "Crimson Boots": "深红靴",
  "Crimson Brush": "深红刷子",
  "Crimson Buckler": "深红圆盾",
  "Crimson Bulwark": "深红盾",
  "Crimson Cheese": "深红奶酪",
  "Crimson Chisel": "深红凿子",
  "Crimson Enhancer": "赤红强化器",
  "Crimson Gauntlets": "深红臂铠",
  "Crimson Hammer": "深红锤",
  "Crimson Hatchet": "深红斧头",
  "Crimson Helmet": "深红头盔",
  "Crimson Mace": "深红狼牙棒",
  "Crimson Milk": "深红牛奶",
  "Crimson Needle": "深红针",
  "Crimson Plate Body": "深红板甲",
  "Crimson Plate Legs": "深红板甲护腿",
  "Crimson Pot": "深红锅",
  "Crimson Shears": "深红剪刀",
  "Crimson Spatula": "深红铲子",
  "Crimson Spear": "深红长枪",
  "Crimson Sword": "深红剑",
  "Crippling Slash": "致残斩",
  "Critical Aura": "暴击光环",
  "Critical Coffee": "暴击咖啡",
  "Crushed Amber": "琥珀碎片",
  "Crushed Amethyst": "紫水晶碎片",
  "Crushed Garnet": "石榴石碎片",
  "Crushed Jade": "翡翠碎片",
  "Crushed Moonstone": "月亮石碎片",
  "Crushed Pearl": "珍珠碎片",
  "Crushed Philosopher's Stone": "贤者之石碎片",
  "Crushed Sunstone": "太阳石碎片",
  "Cupcake": "纸杯蛋糕",
  "Cursed Ball": "诅咒之球",
  "Cursed Bow": "咒怨之弓",
  "Dairyhand's Bottoms": "挤奶工的下装",
  "Dairyhand's Top": "挤奶工的上衣",
  "Dark Key Fragment": "黑暗钥匙碎片",
  "Defense Coffee": "防御咖啡",
  "Demonic Core": "恶魔核心",
  "Demonic Plate Body": "恶魔板甲",
  "Demonic Plate Legs": "恶魔板甲护腿",
  "Dodocamel Gauntlets": "渡驼护手",
  "Dodocamel Plume": "渡驼之羽",
  "Donut": "甜甜圈",
  "Dragon Fruit": "火龙果",
  "Dragon Fruit Gummy": "火龙果软糖",
  "Dragon Fruit Yogurt": "火龙果酸奶",
  "Earrings Of Armor": "护甲耳环",
  "Earrings Of Critical Strike": "暴击耳环",
  "Earrings Of Essence Find": "精华发现耳环",
  "Earrings Of Gathering": "采集耳环",
  "Earrings Of Rare Find": "稀有发现耳环",
  "Earrings Of Regeneration": "回复耳环",
  "Earrings Of Resistance": "抗性耳环",
  "Efficiency Tea": "效率茶",
  "Egg": "鸡蛋",
  "Elemental Affinity": "元素亲和",
  "Elusiveness": "闪避",
  "Emp Tea Leaf": "虚空茶叶",
  "Enchanted Chest": "秘法宝箱",
  "Enchanted Chest Key": "秘法宝箱钥匙",
  "Enchanted Cloak": "秘法披风",
  "Enchanted Entry Key": "秘法钥匙",
  "Enchanted Essence": "秘法精华",
  "Enchanted Gloves": "附魔手套",
  "Enchanted Token": "秘法代币",
  "Enhancer's Bottoms": "强化师的下装",
  "Enhancer's Top": "强化师的上衣",
  "Enhancing Essence": "强化精华",
  "Enhancing Tea": "强化茶",
  "Entangle": "缠绕",
  "Excelsa Coffee Bean": "高级咖啡豆",
  "Expert Task Badge": "专家任务徽章",
  "Eye Of The Watcher": "观察者之眼",
  "Eye Watch": "掌上监工",
  "Eyessence": "眼球精华",
  "Fierce Aura": "物理光环",
  "Fieriosa Coffee Bean": "火山咖啡豆",
  "Fighter Necklace": "战士项链",
  "Fireball": "火球",
  "Firestorm": "火焰风暴(群体)",
  "Flame Arrow": "烈焰箭",
  "Flame Aura": "火焰光环",
  "Flame Blast": "熔岩爆裂(群体)",
  "Flaming Cloth": "烈焰碎布",
  "Flaming Robe Bottoms": "烈焰衬裙",
  "Flaming Robe Top": "烈焰长袍",
  "Flax": "亚麻",
  "Fluffy Red Hat": "蓬松红帽子",
  "Forager's Bottoms": "采摘者的下装",
  "Forager's Top": "采摘者的上衣",
  "Foraging Essence": "采摘精华",
  "Foraging Tea": "采摘茶",
  "Frenzy": "狂热",
  "Frost Sphere": "冰霜球",
  "Frost Staff": "冰霜法杖",
  "Frost Surge": "冰霜爆裂(群体)",
  "Garnet": "石榴石",
  "Gathering Tea": "采集茶",
  "Gator Vest": "鳄鱼背心",
  "Giant Pouch": "巨大袋子",
  "Ginkgo Bow": "银杏弓",
  "Ginkgo Crossbow": "银杏弩",
  "Ginkgo Fire Staff": "银杏火法杖",
  "Ginkgo Log": "银杏原木",
  "Ginkgo Lumber": "银杏木板",
  "Ginkgo Nature Staff": "银杏自然法杖",
  "Ginkgo Shield": "银杏盾",
  "Ginkgo Water Staff": "银杏水法杖",
  "Gluttonous Energy": "贪食能量",
  "Gluttonous Pouch": "贪食之袋",
  "Gobo Boomstick": "哥布林火枪",
  "Gobo Boots": "哥布林靴",
  "Gobo Bracers": "哥布林护腕",
  "Gobo Chaps": "哥布林护腿",
  "Gobo Defender": "哥布林防御者",
  "Gobo Essence": "哥布林精华",
  "Gobo Hide": "哥布林皮",
  "Gobo Hood": "哥布林兜帽",
  "Gobo Leather": "哥布林皮革",
  "Gobo Rag": "哥布林破布",
  "Gobo Shooter": "哥布林弹弓",
  "Gobo Slasher": "哥布林关刀",
  "Gobo Smasher": "哥布林狼牙棒",
  "Gobo Stabber": "哥布林长剑",
  "Gobo Tunic": "哥布林束腰",
  "Goggles": "护目镜",
  "Golem Essence": "魔像精华",
  "Gourmet Tea": "双倍茶",
  "Granite Bludgeon": "花岗岩大棒",
  "Green Key Fragment": "绿色钥匙碎片",
  "Green Tea Leaf": "绿茶叶",
  "Griffin Bulwark": "狮鹫盾",
  "Griffin Chaps": "狮鹫护腿",
  "Griffin Leather": "狮鹫之皮",
  "Griffin Talon": "狮鹫之爪",
  "Griffin Tunic": "狮鹫紧身衣",
  "Grizzly Bear Fluff": "灰熊绒",
  "Grizzly Bear Shoes": "灰熊鞋",
  "Gummy": "软糖",
  "Guzzling Energy": "暴饮能量",
  "Guzzling Pouch": "暴饮之囊",
  "Heal": "自愈术",
  "Holy Alembic": "神圣蒸馏器",
  "Holy Boots": "神圣靴",
  "Holy Brush": "神圣刷子",
  "Holy Buckler": "神圣圆盾",
  "Holy Bulwark": "神圣盾",
  "Holy Cheese": "神圣奶酪",
  "Holy Chisel": "神圣凿子",
  "Holy Enhancer": "神圣强化器",
  "Holy Gauntlets": "神圣臂铠",
  "Holy Hammer": "神圣锤",
  "Holy Hatchet": "神圣斧头",
  "Holy Helmet": "神圣头盔",
  "Holy Mace": "神圣狼牙棒",
  "Holy Milk": "神圣牛奶",
  "Holy Needle": "神圣针",
  "Holy Plate Body": "神圣板甲",
  "Holy Plate Legs": "神圣板甲护腿",
  "Holy Pot": "神圣锅",
  "Holy Shears": "神圣剪刀",
  "Holy Spatula": "神圣铲子",
  "Holy Spear": "神圣长枪",
  "Holy Sword": "神圣剑",
  "Ice Spear": "冰枪术",
  "Icy Cloth": "冰霜碎布",
  "Icy Robe Bottoms": "冰霜衬裙",
  "Icy Robe Top": "冰霜长袍",
  "Impale": "透骨之刺",
  "Infernal Battlestaff": "炼狱法杖",
  "Infernal Ember": "地狱余烬",
  "Insanity": "疯狂",
  "Intelligence Coffee": "智力咖啡",
  "Invincible": "无敌",
  "Jackalope Antler": "鹿角兔之角",
  "Jackalope Staff": "鹿角兔之杖",
  "Jade": "翡翠",
  "Jungle Essence": "丛林精华",
  "Knight's Aegis": "骑士盾",
  "Knight's Ingot": "骑士之锭",
  "Large Artisan's Crate": "匠心巧匣【大】",
  "Large Meteorite Cache": "星坠遗藏【大】",
  "Large Pouch": "大袋子",
  "Large Treasure Chest": "宝箱【大】",
  "Liberica Coffee Bean": "中级咖啡豆",
  "Linen Boots": "亚麻靴",
  "Linen Fabric": "亚麻布料",
  "Linen Gloves": "亚麻手套",
  "Linen Hat": "亚麻帽",
  "Linen Robe Bottoms": "亚麻衬裙",
  "Linen Robe Top": "亚麻上衣",
  "Living Granite": "花岗岩",
  "Log": "普通原木",
  "Lucky Coffee": "幸运咖啡",
  "Lumber": "普通木板",
  "Lumberjack's Bottoms": "伐木工的下装",
  "Lumberjack's Top": "伐木工的上衣",
  "Luna Robe Bottoms": "月神衬裙",
  "Luna Robe Top": "月神长袍",
  "Luna Wing": "月神翼",
  "Magic Coffee": "魔法咖啡",
  "Magician's Cloth": "魔术师碎布",
  "Magician's Hat": "魔术师之帽",
  "Magnet": "磁铁",
  "Magnetic Gloves": "磁力手套",
  "Magnifying Glass": "放大镜",
  "Maim": "血刃斩",
  "Mana Spring": "法力喷泉(群体)",
  "Manticore Shield": "蝎狮盾",
  "Manticore Sting": "蝎狮之刺",
  "Marine Chaps": "航海护腿",
  "Marine Scale": "海洋鳞片",
  "Marine Tunic": "航海束腰",
  "Marsberry": "火星梅",
  "Marsberry Cake": "火星莓蛋糕",
  "Marsberry Donut": "火星莓甜甜圈",
  "Medium Artisan's Crate": "匠心巧匣【中】",
  "Medium Meteorite Cache": "星坠遗藏【中】",
  "Medium Pouch": "中袋子",
  "Medium Treasure Chest": "宝箱【中】",
  "Milk": "牛奶",
  "Milking Essence": "挤奶精华",
  "Milking Tea": "挤奶茶",
  "Minor Heal": "次级自愈术",
  "Mirror Of Protection": "保护之镜",
  "Mooberry": "月梅",
  "Mooberry Cake": "月莓蛋糕",
  "Mooberry Donut": "月莓甜甜圈",
  "Moolong Tea Leaf": "月亮茶叶",
  "Moonstone": "月亮石",
  "Nature's Veil": "自然菌幕(群体)",
  "Necklace Of Efficiency": "效率项链",
  "Necklace Of Speed": "速度项链",
  "Necklace Of Wisdom": "经验项链",
  "Orange": "橙子",
  "Orange Gummy": "橙子软糖",
  "Orange Key Fragment": "橙色钥匙碎片",
  "Orange Yogurt": "橙子酸奶",
  "Panda Fluff": "熊猫绒",
  "Panda Gloves": "熊猫手套",
  "Peach": "桃子",
  "Peach Gummy": "桃子软糖",
  "Peach Yogurt": "桃子酸奶",
  "Pearl": "珍珠",
  "Penetrating Shot": "贯穿射击(贯穿)",
  "Penetrating Strike": "贯心之刺(贯穿)",
  "Pestilent Shot": "疫病射击",
  "Philosopher's Earrings": "贤者耳环",
  "Philosopher's Necklace": "贤者项链",
  "Philosopher's Ring": "贤者戒指",
  "Philosopher's Stone": "贤者之石",
  "Pincer Gloves": "螯钳手套",
  "Plum": "李子",
  "Plum Gummy": "李子软糖",
  "Plum Yogurt": "李子酸奶",
  "Poke": "破胆之刺",
  "Polar Bear Fluff": "北极熊绒",
  "Polar Bear Shoes": "北极熊鞋",
  "Power Coffee": "力量咖啡",
  "Precision": "精确",
  "Prime Catalyst": "主要催化剂",
  "Processing Tea": "加工茶",
  "Provoke": "挑衅",
  "Puncture": "破甲之刺",
  "Purple Key Fragment": "紫色钥匙碎片",
  "Purpleheart Bow": "紫心弓",
  "Purpleheart Crossbow": "紫心弩",
  "Purpleheart Fire Staff": "紫心火法杖",
  "Purpleheart Log": "紫心原木",
  "Purpleheart Lumber": "紫心木板",
  "Purpleheart Nature Staff": "紫心自然法杖",
  "Purpleheart Shield": "紫心木盾",
  "Purpleheart Water Staff": "紫心水法杖",
  "Purple's Gift": "牛紫的礼物",
  "Quick Aid": "快速治疗术",
  "Quick Shot": "快速射击",
  "Radiant Boots": "光辉靴",
  "Radiant Fabric": "光辉布料",
  "Radiant Fiber": "光辉纤维",
  "Radiant Gloves": "光辉手套",
  "Radiant Hat": "光辉帽",
  "Radiant Robe Bottoms": "光辉衬裙",
  "Radiant Robe Top": "光辉上衣",
  "Rain Of Arrows": "箭雨（群体）",
  "Rainbow Alembic": "彩虹蒸馏器",
  "Rainbow Boots": "彩虹靴",
  "Rainbow Brush": "彩虹刷子",
  "Rainbow Buckler": "彩虹圆盾",
  "Rainbow Bulwark": "彩虹盾",
  "Rainbow Cheese": "彩虹奶酪",
  "Rainbow Chisel": "彩虹凿子",
  "Rainbow Enhancer": "彩虹强化器",
  "Rainbow Gauntlets": "彩虹臂铠",
  "Rainbow Hammer": "彩虹锤",
  "Rainbow Hatchet": "彩虹斧头",
  "Rainbow Helmet": "彩虹头盔",
  "Rainbow Mace": "彩虹狼牙棒",
  "Rainbow Milk": "彩虹牛奶",
  "Rainbow Needle": "彩虹针",
  "Rainbow Plate Body": "彩虹板甲",
  "Rainbow Plate Legs": "彩虹板甲护腿",
  "Rainbow Pot": "彩虹锅",
  "Rainbow Shears": "彩虹剪刀",
  "Rainbow Spatula": "彩虹铲子",
  "Rainbow Spear": "彩虹长枪",
  "Rainbow Sword": "彩虹剑",
  "Ranged Coffee": "远程咖啡",
  "Ranger Necklace": "游侠项链",
  "Red Culinary Hat": "红色厨师帽",
  "Red Panda Fluff": "小熊猫绒",
  "Red Tea Leaf": "红茶叶",
  "Redwood Bow": "红杉弓",
  "Redwood Crossbow": "红杉弩",
  "Redwood Fire Staff": "红杉火法杖",
  "Redwood Log": "红杉原木",
  "Redwood Lumber": "红杉木板",
  "Redwood Nature Staff": "红杉自然法杖",
  "Redwood Shield": "红杉盾",
  "Redwood Water Staff": "红杉水法杖",
  "Regal Jewel": "君王宝石",
  "Regal Sword": "君王之剑",
  "Rejuvenate": "群体治疗术",
  "Reptile Boots": "爬行动物靴",
  "Reptile Bracers": "爬行动物护腕",
  "Reptile Chaps": "爬行动物护腿",
  "Reptile Hide": "爬行动物皮",
  "Reptile Hood": "爬行动物兜帽",
  "Reptile Leather": "爬行动物皮革",
  "Reptile Tunic": "爬行动物束腰",
  "Revenant Anima": "亡者之魂",
  "Revenant Chaps": "亡灵护腿",
  "Revenant Tunic": "亡灵外套",
  "Revive": "复活",
  "Ring Of Armor": "护甲戒指",
  "Ring Of Critical Strike": "暴击戒指",
  "Ring Of Essence Find": "精华发现戒指",
  "Ring Of Gathering": "采集戒指",
  "Ring Of Rare Find": "稀有发现戒指",
  "Ring Of Regeneration": "回复戒指",
  "Ring Of Resistance": "抗性戒指",
  "Robusta Coffee Bean": "低级咖啡豆",
  "Rough Boots": "粗糙靴",
  "Rough Bracers": "粗糙护腕",
  "Rough Chaps": "粗糙护腿",
  "Rough Hide": "粗糙兽皮",
  "Rough Hood": "粗糙兜帽",
  "Rough Leather": "粗糙皮革",
  "Rough Tunic": "粗糙束腰",
  "Royal Cloth": "皇家碎布",
  "Royal Fire Robe Bottoms": "皇家火焰衬裙",
  "Royal Fire Robe Top": "皇家火焰长袍",
  "Royal Nature Robe Bottoms": "皇家自然衬裙",
  "Royal Nature Robe Top": "皇家自然长袍",
  "Royal Water Robe Bottoms": "皇家流水衬裙",
  "Royal Water Robe Top": "皇家流水长袍",
  "Scratch": "爪影斩",
  "Shard Of Protection": "保护碎片",
  "Shoebill Feather": "大嘴鹳羽毛",
  "Shoebill Shoes": "大嘴鹳鞋",
  "Sighted Bracers": "瞄准护腕",
  "Silencing Shot": "沉默之箭",
  "Silk Boots": "丝靴",
  "Silk Fabric": "丝绸",
  "Silk Gloves": "丝手套",
  "Silk Hat": "丝帽",
  "Silk Robe Bottoms": "丝绸衬裙",
  "Silk Robe Top": "丝绸上衣",
  "Sinister Cape": "邪恶斗篷",
  "Sinister Chest": "邪恶宝箱",
  "Sinister Chest Key": "邪恶宝箱钥匙",
  "Sinister Entry Key": "邪恶钥匙",
  "Sinister Essence": "邪恶精华",
  "Sinister Token": "邪恶代币",
  "Smack": "重碾",
  "Small Artisan's Crate": "匠心巧匣【小】",
  "Small Meteorite Cache": "星坠遗藏【小】",
  "Small Pouch": "小袋子",
  "Small Treasure Chest": "宝箱【小】",
  "Smoke Burst": "爆尘灭影",
  "Snail Shell": "蜗牛壳",
  "Snail Shell Helmet": "蜗牛壳头盔",
  "Snake Fang": "蛇牙",
  "Snake Fang Dirk": "蛇牙短剑",
  "Sorcerer Boots": "巫师靴",
  "Sorcerer Essence": "法师精华",
  "Sorcerer's Sole": "魔法师的鞋底",
  "Soul Fragment": "灵魂碎片",
  "Soul Hunter Crossbow": "灵魂猎手弩",
  "Spaceberry": "太空梅",
  "Spaceberry Cake": "太空莓蛋糕",
  "Spaceberry Donut": "太空莓甜甜圈",
  "Spacia Coffee Bean": "太空咖啡豆",
  "Speed Aura": "速度光环",
  "Spike Shell": "尖刺防护",
  "Spiked Bulwark": "尖刺盾",
  "Stalactite Shard": "钟乳石碎片",
  "Stalactite Spear": "石钟长枪",
  "Stamina Coffee": "耐力咖啡",
  "Star Fragment": "星光碎片",
  "Star Fruit": "杨桃",
  "Star Fruit Gummy": "杨桃软糖",
  "Star Fruit Yogurt": "杨桃酸奶",
  "Steady Shot": "稳定射击",
  "Stone Key Fragment": "石头钥匙碎片",
  "Strawberry": "草莓",
  "Strawberry Cake": "草莓蛋糕",
  "Strawberry Donut": "草莓甜甜圈",
  "Stunning Blow": "重锤",
  "Sugar": "糖",
  "Sundering Crossbow": "裂空之弩",
  "Sundering Jewel": "裂空宝石",
  "Sunstone": "太阳石",
  "Super Alchemy Tea": "超级炼金茶",
  "Super Attack Coffee": "超级攻击咖啡",
  "Super Brewing Tea": "超级冲泡茶",
  "Super Cheesesmithing Tea": "超级奶酪锻造茶",
  "Super Cooking Tea": "超级烹饪茶",
  "Super Crafting Tea": "超级制作茶",
  "Super Defense Coffee": "超级防御咖啡",
  "Super Enhancing Tea": "超级强化茶",
  "Super Foraging Tea": "超级采摘茶",
  "Super Intelligence Coffee": "超级智力咖啡",
  "Super Magic Coffee": "超级魔法咖啡",
  "Super Milking Tea": "超级挤奶茶",
  "Super Power Coffee": "超级力量咖啡",
  "Super Ranged Coffee": "超级远程咖啡",
  "Super Stamina Coffee": "超级耐力咖啡",
  "Super Tailoring Tea": "超级裁缝茶",
  "Super Woodcutting Tea": "超级伐木茶",
  "Swamp Essence": "沼泽精华",
  "Sweep": "重扫(群体)",
  "Swiftness Coffee": "迅捷咖啡",
  "Sylvan Aura": "自然光环",
  "Tailoring Essence": "裁缝精华",
  "Tailoring Tea": "裁缝茶",
  "Tailor's Bottoms": "裁缝的下装",
  "Tailor's Top": "裁缝的上衣",
  "Task Crystal": "任务水晶",
  "Task Token": "任务代币",
  "Taunt": "嘲讽",
  "Thread Of Expertise": "专精之线",
  "Tome Of Healing": "治疗之书",
  "Tome Of The Elements": "元素之书",
  "Toughness": "坚韧",
  "Toxic Pollen": "剧毒粉尘(群体)",
  "Treant Bark": "树皮",
  "Treant Shield": "树人盾",
  "Turtle Shell": "乌龟壳",
  "Turtle Shell Body": "龟壳板甲",
  "Turtle Shell Legs": "龟壳护腿",
  "Twilight Essence": "暮光精华",
  "Ultra Alchemy Tea": "究极炼金茶",
  "Ultra Attack Coffee": "究极攻击咖啡",
  "Ultra Brewing Tea": "究极冲泡茶",
  "Ultra Cheesesmithing Tea": "究极奶酪锻造茶",
  "Ultra Cooking Tea": "究极烹饪茶",
  "Ultra Crafting Tea": "究极制作茶",
  "Ultra Defense Coffee": "究极防御咖啡",
  "Ultra Enhancing Tea": "究极强化茶",
  "Ultra Foraging Tea": "究极采摘茶",
  "Ultra Intelligence Coffee": "究极智力咖啡",
  "Ultra Magic Coffee": "究极魔法咖啡",
  "Ultra Milking Tea": "究极挤奶茶",
  "Ultra Power Coffee": "究极力量咖啡",
  "Ultra Ranged Coffee": "究极远程咖啡",
  "Ultra Stamina Coffee": "究极耐力咖啡",
  "Ultra Tailoring Tea": "究极裁缝茶",
  "Ultra Woodcutting Tea": "究极伐木茶",
  "Umbral Boots": "暗影靴",
  "Umbral Bracers": "暗影护腕",
  "Umbral Chaps": "暗影护腿",
  "Umbral Hide": "暗影皮",
  "Umbral Hood": "暗影兜帽",
  "Umbral Leather": "暗影皮革",
  "Umbral Tunic": "暗影束腰",
  "Vampire Fang": "吸血鬼之牙",
  "Vampire Fang Dirk": "吸血鬼短剑",
  "Vampiric Bow": "吸血弓",
  "Vampirism": "吸血",
  "Verdant Alembic": "翠绿蒸馏器",
  "Verdant Boots": "翠绿靴",
  "Verdant Brush": "翠绿刷子",
  "Verdant Buckler": "翠绿圆盾",
  "Verdant Bulwark": "翠绿盾",
  "Verdant Cheese": "翠绿奶酪",
  "Verdant Chisel": "翠绿凿子",
  "Verdant Enhancer": "翠绿强化器",
  "Verdant Gauntlets": "翠绿臂铠",
  "Verdant Hammer": "翠绿锤",
  "Verdant Hatchet": "翠绿斧头",
  "Verdant Helmet": "翠绿头盔",
  "Verdant Mace": "翠绿狼牙棒",
  "Verdant Milk": "翠绿牛奶",
  "Verdant Needle": "翠绿针",
  "Verdant Plate Body": "翠绿板甲",
  "Verdant Plate Legs": "翠绿板甲护腿",
  "Verdant Pot": "翠绿锅",
  "Verdant Shears": "翠绿剪刀",
  "Verdant Spatula": "翠绿铲子",
  "Verdant Spear": "翠绿长枪",
  "Verdant Sword": "翠绿剑",
  "Vision Helmet": "视觉头盔",
  "Vision Shield": "视觉盾",
  "Watchful Relic": "警戒遗物",
  "Water Strike": "流水冲击",
  "Werewolf Claw": "狼人之爪",
  "Werewolf Slasher": "狼人关刀",
  "Wheat": "小麦",
  "White Key Fragment": "白色钥匙碎片",
  "Wisdom Coffee": "经验咖啡",
  "Wisdom Tea": "经验茶",
  "Wizard Necklace": "巫师项链",
  "Woodcutting Essence": "伐木精华",
  "Woodcutting Tea": "伐木茶",
  "Wooden Bow": "木弓",
  "Wooden Crossbow": "木弩",
  "Wooden Fire Staff": "木火法杖",
  "Wooden Nature Staff": "木制自然法杖",
  "Wooden Shield": "木盾",
  "Wooden Water Staff": "木制水法杖",
  "Yogurt": "酸奶"
}
